/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminFacultyRouteImport } from './routes/_authenticated/admin/faculty'
import { Route as AuthenticatedAdminGenerateRouteImport } from './routes/_authenticated/admin/generate'
import { Route as AuthenticatedAdminRoomsRouteImport } from './routes/_authenticated/admin/rooms'
import { Route as AuthenticatedAdminSemesterRouteImport } from './routes/_authenticated/admin/semester'
import { Route as AuthenticatedAdminTimetableRouteImport } from './routes/_authenticated/admin/timetable'
import { Route as AuthenticatedFacultyDashboardRouteImport } from './routes/_authenticated/faculty/dashboard'
import { Route as AuthenticatedFacultyTimetableRouteImport } from './routes/_authenticated/faculty/timetable'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student/dashboard'
import { Route as AuthenticatedStudentTimetableRouteImport } from './routes/_authenticated/student/timetable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFacultyRoute =
  AuthenticatedAdminFacultyRouteImport.update({
    id: '/admin/faculty',
    path: '/admin/faculty',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGenerateRoute =
  AuthenticatedAdminGenerateRouteImport.update({
    id: '/admin/generate',
    path: '/admin/generate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoomsRoute = AuthenticatedAdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSemesterRoute =
  AuthenticatedAdminSemesterRouteImport.update({
    id: '/admin/semester',
    path: '/admin/semester',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTimetableRoute =
  AuthenticatedAdminTimetableRouteImport.update({
    id: '/admin/timetable',
    path: '/admin/timetable',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacultyDashboardRoute =
  AuthenticatedFacultyDashboardRouteImport.update({
    id: '/faculty/dashboard',
    path: '/faculty/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacultyTimetableRoute =
  AuthenticatedFacultyTimetableRouteImport.update({
    id: '/faculty/timetable',
    path: '/faculty/timetable',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/student/dashboard',
    path: '/student/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentTimetableRoute =
  AuthenticatedStudentTimetableRouteImport.update({
    id: '/student/timetable',
    path: '/student/timetable',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/semester': typeof AuthenticatedAdminSemesterRoute
  '/admin/timetable': typeof AuthenticatedAdminTimetableRoute
  '/faculty/dashboard': typeof AuthenticatedFacultyDashboardRoute
  '/faculty/timetable': typeof AuthenticatedFacultyTimetableRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/timetable': typeof AuthenticatedStudentTimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/semester': typeof AuthenticatedAdminSemesterRoute
  '/admin/timetable': typeof AuthenticatedAdminTimetableRoute
  '/faculty/dashboard': typeof AuthenticatedFacultyDashboardRoute
  '/faculty/timetable': typeof AuthenticatedFacultyTimetableRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/timetable': typeof AuthenticatedStudentTimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/_authenticated/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/_authenticated/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/_authenticated/admin/semester': typeof AuthenticatedAdminSemesterRoute
  '/_authenticated/admin/timetable': typeof AuthenticatedAdminTimetableRoute
  '/_authenticated/faculty/dashboard': typeof AuthenticatedFacultyDashboardRoute
  '/_authenticated/faculty/timetable': typeof AuthenticatedFacultyTimetableRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/timetable': typeof AuthenticatedStudentTimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/faculty'
    | '/admin/generate'
    | '/admin/rooms'
    | '/admin/semester'
    | '/admin/timetable'
    | '/faculty/dashboard'
    | '/faculty/timetable'
    | '/student/dashboard'
    | '/student/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/faculty'
    | '/admin/generate'
    | '/admin/rooms'
    | '/admin/semester'
    | '/admin/timetable'
    | '/faculty/dashboard'
    | '/faculty/timetable'
    | '/student/dashboard'
    | '/student/timetable'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/faculty'
    | '/_authenticated/admin/generate'
    | '/_authenticated/admin/rooms'
    | '/_authenticated/admin/semester'
    | '/_authenticated/admin/timetable'
    | '/_authenticated/faculty/dashboard'
    | '/_authenticated/faculty/timetable'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/faculty': {
      id: '/_authenticated/admin/faculty'
      path: '/admin/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AuthenticatedAdminFacultyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/generate': {
      id: '/_authenticated/admin/generate'
      path: '/admin/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AuthenticatedAdminGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/rooms': {
      id: '/_authenticated/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AuthenticatedAdminRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/semester': {
      id: '/_authenticated/admin/semester'
      path: '/admin/semester'
      fullPath: '/admin/semester'
      preLoaderRoute: typeof AuthenticatedAdminSemesterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/timetable': {
      id: '/_authenticated/admin/timetable'
      path: '/admin/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AuthenticatedAdminTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faculty/dashboard': {
      id: '/_authenticated/faculty/dashboard'
      path: '/faculty/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof AuthenticatedFacultyDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faculty/timetable': {
      id: '/_authenticated/faculty/timetable'
      path: '/faculty/timetable'
      fullPath: '/faculty/timetable'
      preLoaderRoute: typeof AuthenticatedFacultyTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/timetable': {
      id: '/_authenticated/student/timetable'
      path: '/student/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof AuthenticatedStudentTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminFacultyRoute: typeof AuthenticatedAdminFacultyRoute
  AuthenticatedAdminGenerateRoute: typeof AuthenticatedAdminGenerateRoute
  AuthenticatedAdminRoomsRoute: typeof AuthenticatedAdminRoomsRoute
  AuthenticatedAdminSemesterRoute: typeof AuthenticatedAdminSemesterRoute
  AuthenticatedAdminTimetableRoute: typeof AuthenticatedAdminTimetableRoute
  AuthenticatedFacultyDashboardRoute: typeof AuthenticatedFacultyDashboardRoute
  AuthenticatedFacultyTimetableRoute: typeof AuthenticatedFacultyTimetableRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentTimetableRoute: typeof AuthenticatedStudentTimetableRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminFacultyRoute: AuthenticatedAdminFacultyRoute,
  AuthenticatedAdminGenerateRoute: AuthenticatedAdminGenerateRoute,
  AuthenticatedAdminRoomsRoute: AuthenticatedAdminRoomsRoute,
  AuthenticatedAdminSemesterRoute: AuthenticatedAdminSemesterRoute,
  AuthenticatedAdminTimetableRoute: AuthenticatedAdminTimetableRoute,
  AuthenticatedFacultyDashboardRoute: AuthenticatedFacultyDashboardRoute,
  AuthenticatedFacultyTimetableRoute: AuthenticatedFacultyTimetableRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentTimetableRoute: AuthenticatedStudentTimetableRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
